// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Raw = {};

function parse(value) {
  var value$1 = value.workspace;
  return {
          workspace: {
            id: value$1.id,
            title: value$1.title
          }
        };
}

function serialize(value) {
  var value$1 = value.workspace;
  var value$2 = value$1.title;
  var value$3 = value$1.id;
  var workspace = {
    id: value$3,
    title: value$2
  };
  return {
          workspace: workspace
        };
}

function verifyArgsAndParse(_WorkspaceData, value) {
  return parse(value);
}

function verifyName(param) {
  
}

var WorkspaceData = {
  Raw: Raw,
  query: "fragment WorkspaceData on Query   {\nworkspace(id: \"123\")  {\nid  \ntitle  \n}\n\n}\n",
  parse: parse,
  serialize: serialize,
  verifyArgsAndParse: verifyArgsAndParse,
  verifyName: verifyName
};

exports.WorkspaceData = WorkspaceData;
/* No side effect */
